### ISSUE TITLE
Inconsistency / Compatibility with Django versions

### ISSUE THREAD

**Issue by robertguetzkow** [zeratul2099/crypt_app#2]
There seems to be some issues regarding the Django dependencies. The commit d6f6389c2425829de61681d7411f2b37b8e0b596 tries to adjust for 1.5+ versions of Django. This is not compatible with the version 1.2.7 which is used in kryptos_install.sh or the version 1.1.1 mentioned in the documentation. This should be fixed by using an appropriate pip-package in the kryptos_install.sh.

**Comment by zeratul2099** [comment]
Should be fixed now. I removed all deprecated install scripts. Installation of dependencies is now with "poetry" and needed django-version is now 1.11.16
